import {
  articleInsertSchema,
  articleSelectSchema,
  articleUpdateSchema,
  ArticleInsertSchema,
  ArticleSelectSchema,
  ArticleUpdateSchema,
  userInsertSchema,
  userSelectSchema,
  userUpdateSchema,
  UserInsertSchema,
  UserSelectSchema,
  UserUpdateSchema,
  rewardInsertSchema,
  rewardSelectSchema,
  rewardUpdateSchema,
  RewardInsertSchema,
  RewardSelectSchema,
  RewardUpdateSchema,
  socialQuestInsertSchema,
  socialQuestSelectSchema,
  socialQuestUpdateSchema,
  SocialQuestInsertSchema,
  SocialQuestSelectSchema,
  SocialQuestUpdateSchema,
  questSubmissionInsertSchema,
  questSubmissionSelectSchema,
  questSubmissionUpdateSchema,
  QuestSubmissionInsertSchema,
  QuestSubmissionSelectSchema,
  QuestSubmissionUpdateSchema,
} from "./schema";

// Export schemas
export { 
  articleInsertSchema, 
  articleSelectSchema, 
  articleUpdateSchema,
  userInsertSchema,
  userSelectSchema,
  userUpdateSchema,
  rewardInsertSchema,
  rewardSelectSchema,
  rewardUpdateSchema,
  socialQuestInsertSchema,
  socialQuestSelectSchema,
  socialQuestUpdateSchema,
  questSubmissionInsertSchema,
  questSubmissionSelectSchema,
  questSubmissionUpdateSchema,
};

// Export types
export type { 
  ArticleInsertSchema, 
  ArticleSelectSchema, 
  ArticleUpdateSchema,
  UserInsertSchema,
  UserSelectSchema,
  UserUpdateSchema,
  RewardInsertSchema,
  RewardSelectSchema,
  RewardUpdateSchema,
  SocialQuestInsertSchema,
  SocialQuestSelectSchema,
  SocialQuestUpdateSchema,
  QuestSubmissionInsertSchema,
  QuestSubmissionSelectSchema,
  QuestSubmissionUpdateSchema,
};
